# must use non-containerized build, because elm-compiler is too slow
# otherwise and using the trick with sysconfcpu breaks sbt
sudo: true
language: scala
scala:
  - 2.12.3

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - sysconfcpus

install:
  - nvm install node
  - nvm use node
  - node --version
  - npm --version
  - npm install -g elm@0.18.0

before_script:
  - export TZ=Europe/Berlin

script:
  - sbt ++$TRAVIS_SCALA_VERSION ";run-all-tests ;make"
