name: Publish Website
on:
  push:
    branches:
      - "current-docs"
jobs:
  publish-website:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Set current version
        run:  echo "SHARRY_VERSION=$(cat version.sbt | grep version | cut -d= -f2 | xargs)" >> $GITHUB_ENV
      - uses: cachix/install-nix-action@26
      - name: Build website (${{ env.SHARRY_VERSION }})
        run: nix develop .#ci --command sbt microsite/makeMicrosite
      - name: Publish website (${{ env.SHARRY_VERSION }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix-shell project/microsite.nix --run "sbt microsite/publishMicrosite"
