name: Publish Website
on:
  push:
    branches:
      - "current-docs"
jobs:
  publish-website:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 0
      - name: Set current version
        run:  echo "SHARRY_VERSION=$(cat version.sbt | grep version | cut -d= -f2 | xargs)" >> $GITHUB_ENV
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-21.05
      - name: Print nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - name: Build website (${{ env.SHARRY_VERSION }})
        run: nix-shell project/microsite.nix --run "sbt microsite/makeMicrosite"
      - name: Publish website (${{ env.SHARRY_VERSION }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix-shell project/microsite.nix --run "sbt microsite/publishMicrosite"
